/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorBingo;
import Modelo.CartonBingo;
import Modelo.ServicioBingo;
import java.awt.Color;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author pxand
 */
public class IFrmBingo extends javax.swing.JInternalFrame implements IVista {
    
    private ControladorBingo controlador;
    private JLabel[][] tombolaLabels;
    private int contadorCartones;
    List<CartonBingo> ganadores;
    /**
     * Creates new form IFrmBingo
     */
    public IFrmBingo(ServicioBingo servicio) {
        initComponents();
        tombolaLabels = new JLabel[5][15];
        inicializarMatrizTombola();
        controlador = new ControladorBingo(servicio,this);
        contadorCartones = 1;
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMenu = new javax.swing.JPanel();
        ModoJuegolbl = new javax.swing.JLabel();
        ModoLlenadolbl = new javax.swing.JLabel();
        ComboJuego = new javax.swing.JComboBox<>();
        ComboLlenado = new javax.swing.JComboBox<>();
        Numerolbl = new javax.swing.JLabel();
        Numerotxtfield = new javax.swing.JTextField();
        Agregarbtn = new javax.swing.JButton();
        Generarbtn = new javax.swing.JButton();
        Desmarcarbtn = new javax.swing.JButton();
        ReiniciarJuegobtn = new javax.swing.JButton();
        NumeroActuallbl = new javax.swing.JLabel();
        AgregarCartonbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelCartones = new javax.swing.JPanel();
        PanelTombola = new javax.swing.JPanel();
        lblNum1 = new javax.swing.JLabel();
        lblNum2 = new javax.swing.JLabel();
        lblNum3 = new javax.swing.JLabel();
        lblNum4 = new javax.swing.JLabel();
        lblNum5 = new javax.swing.JLabel();
        lblNum6 = new javax.swing.JLabel();
        lblNum7 = new javax.swing.JLabel();
        lblNum8 = new javax.swing.JLabel();
        lblNum9 = new javax.swing.JLabel();
        lblNum10 = new javax.swing.JLabel();
        lblNum11 = new javax.swing.JLabel();
        lblNum12 = new javax.swing.JLabel();
        lblNum13 = new javax.swing.JLabel();
        lblNum14 = new javax.swing.JLabel();
        lblNum15 = new javax.swing.JLabel();
        lblNum16 = new javax.swing.JLabel();
        lblNum17 = new javax.swing.JLabel();
        lblNum18 = new javax.swing.JLabel();
        lblNum19 = new javax.swing.JLabel();
        lblNum20 = new javax.swing.JLabel();
        lblNum21 = new javax.swing.JLabel();
        lblNum22 = new javax.swing.JLabel();
        lblNum23 = new javax.swing.JLabel();
        lblNum24 = new javax.swing.JLabel();
        lblNum25 = new javax.swing.JLabel();
        lblNum26 = new javax.swing.JLabel();
        lblNum27 = new javax.swing.JLabel();
        lblNum28 = new javax.swing.JLabel();
        lblNum29 = new javax.swing.JLabel();
        lblNum30 = new javax.swing.JLabel();
        lblNum31 = new javax.swing.JLabel();
        lblNum32 = new javax.swing.JLabel();
        lblNum33 = new javax.swing.JLabel();
        lblNum34 = new javax.swing.JLabel();
        lblNum35 = new javax.swing.JLabel();
        lblNum36 = new javax.swing.JLabel();
        lblNum37 = new javax.swing.JLabel();
        lblNum38 = new javax.swing.JLabel();
        lblNum39 = new javax.swing.JLabel();
        lblNum40 = new javax.swing.JLabel();
        lblNum41 = new javax.swing.JLabel();
        lblNum42 = new javax.swing.JLabel();
        lblNum43 = new javax.swing.JLabel();
        lblNum44 = new javax.swing.JLabel();
        lblNum45 = new javax.swing.JLabel();
        lblNum46 = new javax.swing.JLabel();
        lblNum47 = new javax.swing.JLabel();
        lblNum48 = new javax.swing.JLabel();
        lblNum49 = new javax.swing.JLabel();
        lblNum50 = new javax.swing.JLabel();
        lblNum51 = new javax.swing.JLabel();
        lblNum52 = new javax.swing.JLabel();
        lblNum53 = new javax.swing.JLabel();
        lblNum54 = new javax.swing.JLabel();
        lblNum55 = new javax.swing.JLabel();
        lblNum56 = new javax.swing.JLabel();
        lblNum57 = new javax.swing.JLabel();
        lblNum58 = new javax.swing.JLabel();
        lblNum59 = new javax.swing.JLabel();
        lblNum60 = new javax.swing.JLabel();
        lblNum61 = new javax.swing.JLabel();
        lblNum62 = new javax.swing.JLabel();
        lblNum63 = new javax.swing.JLabel();
        lblNum64 = new javax.swing.JLabel();
        lblNum65 = new javax.swing.JLabel();
        lblNum66 = new javax.swing.JLabel();
        lblNum67 = new javax.swing.JLabel();
        lblNum68 = new javax.swing.JLabel();
        lblNum69 = new javax.swing.JLabel();
        lblNum70 = new javax.swing.JLabel();
        lblNum71 = new javax.swing.JLabel();
        lblNum72 = new javax.swing.JLabel();
        lblNum73 = new javax.swing.JLabel();
        lblNum74 = new javax.swing.JLabel();
        lblNum75 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(1920, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));

        PanelMenu.setBackground(new java.awt.Color(51, 51, 51));
        PanelMenu.setMinimumSize(new java.awt.Dimension(858, 79));
        PanelMenu.setPreferredSize(new java.awt.Dimension(858, 79));

        ModoJuegolbl.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ModoJuegolbl.setText("Modo de Juego");

        ModoLlenadolbl.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ModoLlenadolbl.setText("Modo de Llenado");

        ComboJuego.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ComboJuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Cuatro Esquinas", "Carton Lleno" }));
        ComboJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboJuegoActionPerformed(evt);
            }
        });

        ComboLlenado.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ComboLlenado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automatico", "Manual" }));
        ComboLlenado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboLlenadoActionPerformed(evt);
            }
        });

        Numerolbl.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Numerolbl.setText("Numero:");

        Numerotxtfield.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Numerotxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumerotxtfieldActionPerformed(evt);
            }
        });

        Agregarbtn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Agregarbtn.setText("Agregar");
        Agregarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarbtnActionPerformed(evt);
            }
        });

        Generarbtn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Generarbtn.setText("Generar Numero");
        Generarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarbtnActionPerformed(evt);
            }
        });

        Desmarcarbtn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Desmarcarbtn.setText("Desmarcar");
        Desmarcarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesmarcarbtnActionPerformed(evt);
            }
        });

        ReiniciarJuegobtn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ReiniciarJuegobtn.setText("Reinciar Juego");
        ReiniciarJuegobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarJuegobtnActionPerformed(evt);
            }
        });

        NumeroActuallbl.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        NumeroActuallbl.setText("Numero Actual:");

        AgregarCartonbtn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        AgregarCartonbtn.setText("Agregar");
        AgregarCartonbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCartonbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ComboJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(ModoJuegolbl)))
                .addGap(36, 36, 36)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addComponent(ModoLlenadolbl)
                        .addGap(84, 84, 84)
                        .addComponent(Numerolbl))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addComponent(ComboLlenado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AgregarCartonbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Agregarbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numerotxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Desmarcarbtn))
                .addGap(27, 27, 27)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Generarbtn)
                    .addComponent(NumeroActuallbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReiniciarJuegobtn)
                .addContainerGap())
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ModoJuegolbl)
                        .addComponent(ModoLlenadolbl))
                    .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NumeroActuallbl)
                        .addComponent(Numerotxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Numerolbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComboLlenado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AgregarCartonbtn)
                        .addComponent(Agregarbtn)
                        .addComponent(Desmarcarbtn)
                        .addComponent(Generarbtn)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addComponent(ReiniciarJuegobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 204));
        jScrollPane1.setViewportView(PanelCartones);

        PanelTombola.setBackground(new java.awt.Color(0, 153, 255));
        PanelTombola.setLayout(new java.awt.GridLayout(5, 15));

        lblNum1.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum1.setText("1");
        lblNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum1);

        lblNum2.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum2.setText("1");
        lblNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum2);

        lblNum3.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum3.setText("1");
        lblNum3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum3);

        lblNum4.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum4.setText("1");
        lblNum4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum4);

        lblNum5.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum5.setText("1");
        lblNum5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum5);

        lblNum6.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum6.setText("1");
        lblNum6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum6);

        lblNum7.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum7.setText("1");
        lblNum7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum7);

        lblNum8.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum8.setText("1");
        lblNum8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum8);

        lblNum9.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum9.setText("1");
        lblNum9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum9);

        lblNum10.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum10.setText("1");
        lblNum10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum10);

        lblNum11.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum11.setText("1");
        lblNum11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum11);

        lblNum12.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum12.setText("1");
        lblNum12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum12);

        lblNum13.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum13.setText("1");
        lblNum13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum13);

        lblNum14.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum14.setText("1");
        lblNum14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum14);

        lblNum15.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum15.setText("1");
        lblNum15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum15);

        lblNum16.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum16.setText("1");
        lblNum16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum16);

        lblNum17.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum17.setText("1");
        lblNum17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum17);

        lblNum18.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum18.setText("1");
        lblNum18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum18);

        lblNum19.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum19.setText("1");
        lblNum19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum19);

        lblNum20.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum20.setText("1");
        lblNum20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum20);

        lblNum21.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum21.setText("1");
        lblNum21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum21);

        lblNum22.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum22.setText("1");
        lblNum22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum22);

        lblNum23.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum23.setText("1");
        lblNum23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum23);

        lblNum24.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum24.setText("1");
        lblNum24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum24);

        lblNum25.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum25.setText("1");
        lblNum25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum25);

        lblNum26.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum26.setText("1");
        lblNum26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum26);

        lblNum27.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum27.setText("1");
        lblNum27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum27);

        lblNum28.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum28.setText("1");
        lblNum28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum28);

        lblNum29.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum29.setText("1");
        lblNum29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum29);

        lblNum30.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum30.setText("1");
        lblNum30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum30);

        lblNum31.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum31.setText("1");
        lblNum31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum31);

        lblNum32.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum32.setText("1");
        lblNum32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum32);

        lblNum33.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum33.setText("1");
        lblNum33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum33);

        lblNum34.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum34.setText("1");
        lblNum34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum34);

        lblNum35.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum35.setText("1");
        lblNum35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum35);

        lblNum36.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum36.setText("1");
        lblNum36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum36);

        lblNum37.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum37.setText("1");
        lblNum37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum37);

        lblNum38.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum38.setText("1");
        lblNum38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum38);

        lblNum39.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum39.setText("1");
        lblNum39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum39);

        lblNum40.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum40.setText("1");
        lblNum40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum40);

        lblNum41.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum41.setText("1");
        lblNum41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum41);

        lblNum42.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum42.setText("1");
        lblNum42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum42);

        lblNum43.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum43.setText("1");
        lblNum43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum43);

        lblNum44.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum44.setText("1");
        lblNum44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum44);

        lblNum45.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum45.setText("1");
        lblNum45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum45);

        lblNum46.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum46.setText("1");
        lblNum46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum46);

        lblNum47.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum47.setText("1");
        lblNum47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum47);

        lblNum48.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum48.setText("1");
        lblNum48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum48);

        lblNum49.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum49.setText("1");
        lblNum49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum49);

        lblNum50.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum50.setText("1");
        lblNum50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum50);

        lblNum51.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum51.setText("1");
        lblNum51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum51);

        lblNum52.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum52.setText("1");
        lblNum52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum52);

        lblNum53.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum53.setText("1");
        lblNum53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum53);

        lblNum54.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum54.setText("1");
        lblNum54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum54);

        lblNum55.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum55.setText("1");
        lblNum55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum55);

        lblNum56.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum56.setText("1");
        lblNum56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum56);

        lblNum57.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum57.setText("1");
        lblNum57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum57);

        lblNum58.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum58.setText("1");
        lblNum58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum58);

        lblNum59.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum59.setText("1");
        lblNum59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum59);

        lblNum60.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum60.setText("1");
        lblNum60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum60);

        lblNum61.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum61.setText("1");
        lblNum61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum61);

        lblNum62.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum62.setText("1");
        lblNum62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum62);

        lblNum63.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum63.setText("1");
        lblNum63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum63);

        lblNum64.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum64.setText("1");
        lblNum64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum64);

        lblNum65.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum65.setText("1");
        lblNum65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum65);

        lblNum66.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum66.setText("1");
        lblNum66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum66);

        lblNum67.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum67.setText("1");
        lblNum67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum67);

        lblNum68.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum68.setText("1");
        lblNum68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum68);

        lblNum69.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum69.setText("1");
        lblNum69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum69);

        lblNum70.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum70.setText("1");
        lblNum70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum70);

        lblNum71.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum71.setText("1");
        lblNum71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum71);

        lblNum72.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum72.setText("1");
        lblNum72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum72);

        lblNum73.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum73.setText("1");
        lblNum73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum73);

        lblNum74.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum74.setText("1");
        lblNum74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum74);

        lblNum75.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        lblNum75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNum75.setText("1");
        lblNum75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelTombola.add(lblNum75);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
            .addComponent(PanelTombola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTombola, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReiniciarJuegobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarJuegobtnActionPerformed
        controlador.reiniciarJuego();
    }//GEN-LAST:event_ReiniciarJuegobtnActionPerformed

    private void DesmarcarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesmarcarbtnActionPerformed
        String numtxtfield = Numerotxtfield.getText();
        if (!numtxtfield.isBlank()){
            int num = Integer.parseInt(Numerotxtfield.getText());
            if (num > 75) {
                mostrarError("El numero no puede ser mayor a 75");
            }
            if (num < 1) {
                mostrarError("El numero no puede ser menor que 1");
            }
            controlador.desmarcarNumero(num);
            
        }else{
           mostrarError("Ingrese un numero antes de desmarcar");
        } 
    }//GEN-LAST:event_DesmarcarbtnActionPerformed

    private void GenerarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarbtnActionPerformed
        controlador.sacarNumero();
    }//GEN-LAST:event_GenerarbtnActionPerformed

    private void AgregarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarbtnActionPerformed
        String numtxtfield = Numerotxtfield.getText();
        if (!numtxtfield.isBlank()){
            int num = Integer.parseInt(Numerotxtfield.getText());
            if (num > 75) {
                mostrarError("El numero no puede ser mayor a 75");
            }
            if (num < 1) {
                mostrarError("El numero no puede ser menor que 1");
            }
            controlador.llamarNumero(num);
            
        }else{
           mostrarError("Ingrese un numero antes de agregar");
        }
    }//GEN-LAST:event_AgregarbtnActionPerformed

    private void NumerotxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumerotxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumerotxtfieldActionPerformed

    private void ComboJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboJuegoActionPerformed
        int opcion = ComboJuego.getSelectedIndex();
        if (opcion == 0) {
            controlador.cambiarModoJuego("Normal");
        }
        if (opcion == 1) {
            controlador.cambiarModoJuego("Cuatro Esquinas");
        }
        if (opcion == 2) {
            controlador.cambiarModoJuego("Carton Lleno");
        }    
        
    }//GEN-LAST:event_ComboJuegoActionPerformed

    private void AgregarCartonbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCartonbtnActionPerformed
        String modoLlenado = String.valueOf(ComboLlenado.getSelectedItem()) ;

        controlador.cambiarModoLlenado(modoLlenado);
        String id = String.valueOf(contadorCartones);
        CartonBingo carton;
        if (modoLlenado.contains("Auto")) {

            carton = controlador.generarCarton(id);
        }
        if (modoLlenado.contains("Manu")) {
            carton = new CartonBingo(String.valueOf(contadorCartones));
            int[][] matriz = new int[5][5];
            for (int fila = 0; fila < 5; fila++) {
                for (int col = 0; col < 5; col++) {
                    if (fila == 2 && col == 2) {
                        matriz[fila][col] = 0;
                    }
                    DialogCartonManual dialog = new DialogCartonManual(null, true, fila, col);
                    dialog.setVisible(true);
                    String valor = dialog.getValorIngresado();
                    if (!valor.isBlank()) {
                        matriz[fila][col] = Integer.parseInt(dialog.getValorIngresado());
                    }
                    if (valor.isBlank()) {
                        mostrarError("No se puede ingresar un valor nulo");
                        break;
                    }
                }
                break;
            }
            carton.setNumeros(matriz);
            if (carton.esValido()) {
                controlador.agregarCartonManual(carton);
            }

        }
    }//GEN-LAST:event_AgregarCartonbtnActionPerformed

    private void ComboLlenadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboLlenadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboLlenadoActionPerformed

    public void anadirPanelCarton(CartonBingo carton) {
        PanelCarton panelCarton = new PanelCarton(carton);
        
        panelCarton.getTitulo2().setText(String.valueOf(contadorCartones));
        contadorCartones++;
        PanelCartones.add(panelCarton);
        PanelCartones.revalidate();
        PanelCartones.repaint();
    }
    
    
    public void marcarNumeroTombola(int numero) {
        if (numero < 1 || numero > 75) {
            return;
        }
        int fila = (numero - 1) / 15;     
        int col = (numero - 1) % 15; 
        JLabel label = tombolaLabels[fila][col];
        label.setForeground(Color.YELLOW);
        NumeroActuallbl.setText("Numero Actual:" + String.valueOf(numero));
    }

    public void limpiarTombola() {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 15; j++) {
                tombolaLabels[i][j].setForeground(Color.BLACK);
                
            }
        }
        NumeroActuallbl.setText("");
    }
    
    private void inicializarMatrizTombola() {

        tombolaLabels[0][0] = lblNum1;
        tombolaLabels[0][1] = lblNum2;
        tombolaLabels[0][2] = lblNum3;
        tombolaLabels[0][3] = lblNum4;
        tombolaLabels[0][4] = lblNum5;
        tombolaLabels[0][5] = lblNum6;
        tombolaLabels[0][6] = lblNum7;
        tombolaLabels[0][7] = lblNum8;
        tombolaLabels[0][8] = lblNum9;
        tombolaLabels[0][9] = lblNum10;
        tombolaLabels[0][10] = lblNum11;
        tombolaLabels[0][11] = lblNum12;
        tombolaLabels[0][12] = lblNum13;
        tombolaLabels[0][13] = lblNum14;
        tombolaLabels[0][14] = lblNum15;

        tombolaLabels[1][0] = lblNum16;
        tombolaLabels[1][1] = lblNum17;
        tombolaLabels[1][2] = lblNum18;
        tombolaLabels[1][3] = lblNum19;
        tombolaLabels[1][4] = lblNum20;
        tombolaLabels[1][5] = lblNum21;
        tombolaLabels[1][6] = lblNum22;
        tombolaLabels[1][7] = lblNum23;
        tombolaLabels[1][8] = lblNum24;
        tombolaLabels[1][9] = lblNum25;
        tombolaLabels[1][10] = lblNum26;
        tombolaLabels[1][11] = lblNum27;
        tombolaLabels[1][12] = lblNum28;
        tombolaLabels[1][13] = lblNum29;
        tombolaLabels[1][14] = lblNum30;

        tombolaLabels[2][0] = lblNum31;
        tombolaLabels[2][1] = lblNum32;
        tombolaLabels[2][2] = lblNum33;
        tombolaLabels[2][3] = lblNum34;
        tombolaLabels[2][4] = lblNum35;
        tombolaLabels[2][5] = lblNum36;
        tombolaLabels[2][6] = lblNum37;
        tombolaLabels[2][7] = lblNum38;
        tombolaLabels[2][8] = lblNum39;
        tombolaLabels[2][9] = lblNum40;
        tombolaLabels[2][10] = lblNum41;
        tombolaLabels[2][11] = lblNum42;
        tombolaLabels[2][12] = lblNum43;
        tombolaLabels[2][13] = lblNum44;
        tombolaLabels[2][14] = lblNum45;

        tombolaLabels[3][0] = lblNum46;
        tombolaLabels[3][1] = lblNum47;
        tombolaLabels[3][2] = lblNum48;
        tombolaLabels[3][3] = lblNum49;
        tombolaLabels[3][4] = lblNum50;
        tombolaLabels[3][5] = lblNum51;
        tombolaLabels[3][6] = lblNum52;
        tombolaLabels[3][7] = lblNum53;
        tombolaLabels[3][8] = lblNum54;
        tombolaLabels[3][9] = lblNum55;
        tombolaLabels[3][10] = lblNum56;
        tombolaLabels[3][11] = lblNum57;
        tombolaLabels[3][12] = lblNum58;
        tombolaLabels[3][13] = lblNum59;
        tombolaLabels[3][14] = lblNum60;

        tombolaLabels[4][0] = lblNum61;
        tombolaLabels[4][1] = lblNum62;
        tombolaLabels[4][2] = lblNum63;
        tombolaLabels[4][3] = lblNum64;
        tombolaLabels[4][4] = lblNum65;
        tombolaLabels[4][5] = lblNum66;
        tombolaLabels[4][6] = lblNum67;
        tombolaLabels[4][7] = lblNum68;
        tombolaLabels[4][8] = lblNum69;
        tombolaLabels[4][9] = lblNum70;
        tombolaLabels[4][10] = lblNum71;
        tombolaLabels[4][11] = lblNum72;
        tombolaLabels[4][12] = lblNum73;
        tombolaLabels[4][13] = lblNum74;
        tombolaLabels[4][14] = lblNum75;

        int num = 1;

        for (int fila = 0; fila < 5; fila++) {
            for (int col = 0; col < 15; col++) {
                tombolaLabels[fila][col].setText(String.valueOf(num));
                num++;
            }
        }
    }
    
    private void actualizarTodosLosCartones() {
        for (java.awt.Component comp : PanelCartones.getComponents()) {
            if (comp instanceof PanelCarton) {
                ((PanelCarton) comp).actualizarMarcados();
            }
        }
    }
    
    public void desmarcarTombola(int numero) {
        if (numero < 1 || numero > 75) {
            return;
        }
        int fila = (numero - 1) / 15;     
        int col = (numero - 1) % 15; 
        JLabel label = tombolaLabels[fila][col];
        label.setForeground(Color.BLACK);
        NumeroActuallbl.setText("Numero Actual:" + String.valueOf(numero));
    }


    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCartonbtn;
    private javax.swing.JButton Agregarbtn;
    private javax.swing.JComboBox<String> ComboJuego;
    private javax.swing.JComboBox<String> ComboLlenado;
    private javax.swing.JButton Desmarcarbtn;
    private javax.swing.JButton Generarbtn;
    private javax.swing.JLabel ModoJuegolbl;
    private javax.swing.JLabel ModoLlenadolbl;
    private javax.swing.JLabel NumeroActuallbl;
    private javax.swing.JLabel Numerolbl;
    private javax.swing.JTextField Numerotxtfield;
    private javax.swing.JPanel PanelCartones;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelTombola;
    private javax.swing.JButton ReiniciarJuegobtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblNum10;
    private javax.swing.JLabel lblNum11;
    private javax.swing.JLabel lblNum12;
    private javax.swing.JLabel lblNum13;
    private javax.swing.JLabel lblNum14;
    private javax.swing.JLabel lblNum15;
    private javax.swing.JLabel lblNum16;
    private javax.swing.JLabel lblNum17;
    private javax.swing.JLabel lblNum18;
    private javax.swing.JLabel lblNum19;
    private javax.swing.JLabel lblNum2;
    private javax.swing.JLabel lblNum20;
    private javax.swing.JLabel lblNum21;
    private javax.swing.JLabel lblNum22;
    private javax.swing.JLabel lblNum23;
    private javax.swing.JLabel lblNum24;
    private javax.swing.JLabel lblNum25;
    private javax.swing.JLabel lblNum26;
    private javax.swing.JLabel lblNum27;
    private javax.swing.JLabel lblNum28;
    private javax.swing.JLabel lblNum29;
    private javax.swing.JLabel lblNum3;
    private javax.swing.JLabel lblNum30;
    private javax.swing.JLabel lblNum31;
    private javax.swing.JLabel lblNum32;
    private javax.swing.JLabel lblNum33;
    private javax.swing.JLabel lblNum34;
    private javax.swing.JLabel lblNum35;
    private javax.swing.JLabel lblNum36;
    private javax.swing.JLabel lblNum37;
    private javax.swing.JLabel lblNum38;
    private javax.swing.JLabel lblNum39;
    private javax.swing.JLabel lblNum4;
    private javax.swing.JLabel lblNum40;
    private javax.swing.JLabel lblNum41;
    private javax.swing.JLabel lblNum42;
    private javax.swing.JLabel lblNum43;
    private javax.swing.JLabel lblNum44;
    private javax.swing.JLabel lblNum45;
    private javax.swing.JLabel lblNum46;
    private javax.swing.JLabel lblNum47;
    private javax.swing.JLabel lblNum48;
    private javax.swing.JLabel lblNum49;
    private javax.swing.JLabel lblNum5;
    private javax.swing.JLabel lblNum50;
    private javax.swing.JLabel lblNum51;
    private javax.swing.JLabel lblNum52;
    private javax.swing.JLabel lblNum53;
    private javax.swing.JLabel lblNum54;
    private javax.swing.JLabel lblNum55;
    private javax.swing.JLabel lblNum56;
    private javax.swing.JLabel lblNum57;
    private javax.swing.JLabel lblNum58;
    private javax.swing.JLabel lblNum59;
    private javax.swing.JLabel lblNum6;
    private javax.swing.JLabel lblNum60;
    private javax.swing.JLabel lblNum61;
    private javax.swing.JLabel lblNum62;
    private javax.swing.JLabel lblNum63;
    private javax.swing.JLabel lblNum64;
    private javax.swing.JLabel lblNum65;
    private javax.swing.JLabel lblNum66;
    private javax.swing.JLabel lblNum67;
    private javax.swing.JLabel lblNum68;
    private javax.swing.JLabel lblNum69;
    private javax.swing.JLabel lblNum7;
    private javax.swing.JLabel lblNum70;
    private javax.swing.JLabel lblNum71;
    private javax.swing.JLabel lblNum72;
    private javax.swing.JLabel lblNum73;
    private javax.swing.JLabel lblNum74;
    private javax.swing.JLabel lblNum75;
    private javax.swing.JLabel lblNum8;
    private javax.swing.JLabel lblNum9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMensaje(String msg, String titulo) {
        javax.swing.JOptionPane.showMessageDialog(this, msg, titulo, javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void mostrarError(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public boolean confirmar(String msg, String titulo) {
        return javax.swing.JOptionPane.showConfirmDialog(this, msg, titulo, 
                javax.swing.JOptionPane.YES_NO_OPTION) == javax.swing.JOptionPane.YES_OPTION;
    }

    @Override
    public void mostrarCarton(CartonBingo carton) {
        anadirPanelCarton(carton);
    }

    @Override
    public void actualizarTombolaV(int numero) {
        marcarNumeroTombola(numero);
        actualizarTodosLosCartones();
    }

    @Override
    public void limpiarTombolaV() {
       limpiarTombola();
       actualizarTodosLosCartones();
    }


    @Override
    public void marcarGanadoresV(List<CartonBingo> ganadores) {
        if (ganadores == null || ganadores.isEmpty()) return;

    String ids = ganadores.stream().map(CartonBingo::getId).collect(java.util.stream.Collectors.joining(", "));

    mostrarMensaje("¡BINGO! Cartones ganadores: " + ids, "¡BINGO!");

    for (java.awt.Component comp : PanelCartones.getComponents()) {
        if (comp instanceof PanelCarton) {
            PanelCarton panel = (PanelCarton) comp;
            if (ganadores.contains(panel.getCarton())) {
                panel.actualizarMarcados();
                panel.actualizarMarcadosGanador();
            }
        }
    }
    }

    @Override
    public void desmarcarTombolaV(int numero) {
        desmarcarTombola(numero);
        actualizarTodosLosCartones();
    }

}
