/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.CartonBingo;
import java.awt.Color;
import static java.lang.String.valueOf;
import javax.swing.JLabel;

/**
 *
 * @author pxand
 */
public class PanelCarton extends javax.swing.JPanel {
    private CartonBingo carton;
    private JLabel[][] labels = new JLabel[5][5];
    
    /**
     * Creates new form Cartones
     */
    
    public PanelCarton(CartonBingo carton) {
        initComponents();
        anadirNumeros(carton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo1 = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        Titulo3 = new javax.swing.JLabel();
        Titulo4 = new javax.swing.JLabel();
        cerrarCarton = new javax.swing.JButton();
        Celda00 = new javax.swing.JLabel();
        Celda01 = new javax.swing.JLabel();
        Celda02 = new javax.swing.JLabel();
        Celda03 = new javax.swing.JLabel();
        Celda04 = new javax.swing.JLabel();
        Celda10 = new javax.swing.JLabel();
        Celda11 = new javax.swing.JLabel();
        Celda12 = new javax.swing.JLabel();
        Celda13 = new javax.swing.JLabel();
        Celda14 = new javax.swing.JLabel();
        Celda20 = new javax.swing.JLabel();
        Celda21 = new javax.swing.JLabel();
        Celda22 = new javax.swing.JLabel();
        Celda23 = new javax.swing.JLabel();
        Celda24 = new javax.swing.JLabel();
        Celda30 = new javax.swing.JLabel();
        Celda31 = new javax.swing.JLabel();
        Celda32 = new javax.swing.JLabel();
        Celda33 = new javax.swing.JLabel();
        Celda34 = new javax.swing.JLabel();
        Celda40 = new javax.swing.JLabel();
        Celda41 = new javax.swing.JLabel();
        Celda42 = new javax.swing.JLabel();
        Celda43 = new javax.swing.JLabel();
        Celda44 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.GridLayout(6, 5));

        Titulo1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setText("Carton:");
        add(Titulo1);

        Titulo2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Titulo2);

        Titulo3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Titulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Titulo3);

        Titulo4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Titulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Titulo4);

        cerrarCarton.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        cerrarCarton.setText("Cerrar");
        cerrarCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarCartonActionPerformed(evt);
            }
        });
        add(cerrarCarton);

        Celda00.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda00);

        Celda01.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda01);

        Celda02.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda02);

        Celda03.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda03);

        Celda04.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda04);

        Celda10.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda10);

        Celda11.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda11);

        Celda12.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda12);

        Celda13.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda13);

        Celda14.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda14);

        Celda20.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda20);

        Celda21.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda21);

        Celda22.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Celda22.setText("FREE");
        add(Celda22);

        Celda23.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda23);

        Celda24.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda24);

        Celda30.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda30);

        Celda31.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda31);

        Celda32.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda32);

        Celda33.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda33);

        Celda34.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda34);

        Celda40.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda40);

        Celda41.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda41);

        Celda42.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda42);

        Celda43.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda43);

        Celda44.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Celda44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(Celda44);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarCartonActionPerformed
        var parent = getParent();
        if (parent != null) {
            parent.remove(this);
            parent.revalidate();
            parent.repaint();
        }
                
    }//GEN-LAST:event_cerrarCartonActionPerformed

    public void anadirNumeros(CartonBingo carton){
        cargarTabla(); 
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if (i == 2 && j == 2) {
                    labels[i][j].setText("Libre");
                } else {
                    labels[i][j].setText(String.valueOf(carton.getNumeros()[i][j]));
                }
            }
        }
    }
    
    public String getCartonBingoId(){
        return carton.getId();
    }
    
    public void actualizarMarcados(){
        boolean[][] marcados = carton.getMarcados();
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if (i == 2 && j == 2) {
                    labels[i][j].setText("FREE");
                } else if (marcados[i][j]) {
                    labels[i][j].setBackground(Color.GREEN);
                    labels[i][j].setForeground(Color.WHITE);
                } else {
                    labels[i][j].setBackground(null);
                    labels[i][j].setForeground(Color.BLACK);
                }
            }
        }
    }
    
    public void marcarGanador(){
        setBackground(Color.RED);
    }
    
    public void desmarcarGanador(){
        setBackground(Color.BLACK);
    }
    
    public void cargarTabla(){
        labels[0][0] = Celda00;
        labels[0][1] = Celda01;
        labels[0][2] = Celda02;
        labels[0][3] = Celda03;
        labels[0][4] = Celda04;
        labels[1][0] = Celda10;
        labels[1][1] = Celda11;
        labels[1][2] = Celda12;
        labels[1][3] = Celda13;
        labels[1][4] = Celda14;
        labels[2][0] = Celda20;
        labels[2][1] = Celda21;
        labels[2][2] = Celda22;
        labels[2][3] = Celda23;
        labels[2][4] = Celda24;
        labels[3][0] = Celda30;
        labels[3][1] = Celda31;
        labels[3][2] = Celda32;
        labels[3][3] = Celda33;
        labels[3][4] = Celda34;
        labels[4][0] = Celda40;
        labels[4][1] = Celda41;
        labels[4][2] = Celda42;
        labels[4][3] = Celda43;
        labels[4][4] = Celda44;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Celda00;
    private javax.swing.JLabel Celda01;
    private javax.swing.JLabel Celda02;
    private javax.swing.JLabel Celda03;
    private javax.swing.JLabel Celda04;
    private javax.swing.JLabel Celda10;
    private javax.swing.JLabel Celda11;
    private javax.swing.JLabel Celda12;
    private javax.swing.JLabel Celda13;
    private javax.swing.JLabel Celda14;
    private javax.swing.JLabel Celda20;
    private javax.swing.JLabel Celda21;
    private javax.swing.JLabel Celda22;
    private javax.swing.JLabel Celda23;
    private javax.swing.JLabel Celda24;
    private javax.swing.JLabel Celda30;
    private javax.swing.JLabel Celda31;
    private javax.swing.JLabel Celda32;
    private javax.swing.JLabel Celda33;
    private javax.swing.JLabel Celda34;
    private javax.swing.JLabel Celda40;
    private javax.swing.JLabel Celda41;
    private javax.swing.JLabel Celda42;
    private javax.swing.JLabel Celda43;
    private javax.swing.JLabel Celda44;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo3;
    private javax.swing.JLabel Titulo4;
    private javax.swing.JButton cerrarCarton;
    // End of variables declaration//GEN-END:variables
}
